spring:
  datasource:
    url: jdbc:postgresql://db:5432/movies_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: prometheus
    metrics:
      export:
        prometheus:
          enabled: true
